### ISSUE TITLE
'components' issues

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/microbit-meteorologist#4]
https://www.raspberrypi.org/learning/microbit-meteorologist/components/usb-microusb/ has a missing image.

https://www.raspberrypi.org/learning/microbit-meteorologist/components/micro-bit/ says "every Year 7 student in the UK:" - the sentence should end with a full-stop instead of a colon.

**Comment by bennuttall** [comment]
Fixed in https://github.com/raspberrypilearning/components/commit/ea4fa4611da1f4daaff833a3b7df96cd760010bd - thanks
